---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012r2
  - name: windows-2008r2

suites:
  - name: default
    run_list:
      - recipe[firewall_test::default]
    attributes:
      dev_mode: true
